name: Build WASM Game with emsdk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pygbag
          git clone https://github.com/emscripten-core/emsdk.git
          git clone https://github.com/pygame-web/pygbag.git
          git clone https://pygame-web.github.io/archives/0.9/pythonrc.py

      # Rimuovi o modifica questa parte se non hai bisogno di scaricare pythonrc.py
      - name: Create game assets directory
        run: mkdir -p p/assets/games/
        # rimuovi la linea wget per pythonrc.py se non è disponibile o necessario
