name: Build WASM Game with emsdk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pygbag
          git clone https://github.com/emscripten-core/emsdk.git

      - name: Make main.py executable
        run: chmod +x p/main.py

      - name: List directory contents
        run: ls -R  # Elenca il contenuto della directory

      - name: Set CI environment variable
        run: echo "CI=true" >> $GITHUB_ENV

      - name: Build WASM Game
        run: |
          echo "Starting the game build..."
          pygbag /home/RobertaMerlo/My_Games/p/main.py -o build/game.wasm -j$(nproc)

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-artifacts
          path: /home/RobertaMerlo/My_Games/p/build/game.wasm
