name: Build WASM Game with emsdk

on:
  push:
    branches:
      - main  # Trigger build on push to main branch
  pull_request:
    branches:
      - main  # Trigger build on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Check out the repository code

      - name: Set up Python environment
        uses: actions/setup-python@v5  # Set up Python
        with:
          python-version: '3.10'  # Specify the required Python version

      - name: Install dependencies
        run: |
          echo "Installing required dependencies..."
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install from requirements.txt
          pip install pygbag  # Install pygbag for WASM compilation

      - name: Make main.py executable
        run: |
          echo "Making main.py executable..."
          chmod +x p/main.py  # Modify the path if necessary

      - name: Set CI environment variable
        run: echo "CI=true" >> $GITHUB_ENV  # Set CI variable

      - name: Check if main.py runs without errors
        run: |
          echo "Checking if main.py runs without errors..."
          python p/main.py  # Test if main.py can be executed without errors

      - name: Build WASM Game
        run: |
          echo "Starting the game build..."
          pygbag p/main.py -o build/game.wasm -j$(nproc)  # Compile using pygbag

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4  # Upload the build artifacts
        with:
          name: wasm-artifacts
          path: build/game.wasm  # Specify the output path for the WASM file
