name: Build WASM Game with emsdk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pygbag

      - name: Clone emsdk and install
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh

      - name: Install pythonrc.py (if needed)
        run: |
          wget https://pygame-web.github.io/archives/0.9/pythonrc.py -P p/assets/games/

      - name: Create game assets directory
        run: mkdir -p p/assets/games/

      - name: Build game with pygbag
        run: pygbag p/main.py
