name: Build WASM Game with emsdk

on:
  push:
    branches:
      - main  # Cambia se necessario
  pull_request:
    branches:
      - main  # Cambia se necessario

jobs:
  build:
    runs-on: ubuntu-latest  # Usa l'ultima versione di Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specifica la versione di Python necessaria

      - name: Install dependencies
        run: |
          echo "Installing required dependencies..."
          pip install -r requirements.txt  # Assicurati di avere un requirements.txt se necessario
          pip install pygbag  # Installa pygbag per la compilazione in WASM

      - name: Make main.py executable
        run: |
          echo "Rendere main.py eseguibile..."
          chmod +x p/main.py  # Modifica il percorso se necessario

      - name: Build WASM Game
        run: |
          echo "Avviando la build del gioco..."
          pygbag p/main.py -o output/game.wasm -j$(nproc)  # Compila usando pygbag

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wasm-artifacts
          path: output/game.wasm  # Modifica in base al tuo output specifico
