name: Build WASM Game with emsdk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pygbag
          git clone https://github.com/emscripten-core/emsdk.git

      # Aggiungi il template e favicon scaricati manualmente
      - name: Add local template and favicon
        run: |
          mkdir -p p/assets/games/
          wget -O p/assets/games/default.tmpl https://pygame-web.github.io/archives/0.9/default.tmpl
          wget -O p/assets/games/favicon.png https://pygame-web.github.io/archives/0.9/favicon.png
          
      - name: Add local pythonrc.py
        run: |
          mkdir -p p/assets/games/
          wget -O p/assets/games/pythonrc.py https://pygame-web.github.io/archives/0.9/pythonrc.py

      - name: Build WASM Game with local template
        run: |
          set -e  # Interrompe se c'è un errore
          set -x  # Abilita logging dettagliato
          echo "Starting the game build with local template..."
          pygbag p/main.py --template p/assets/games/default.tmpl

      - name: List directory contents after build
        run: ls -R build || echo "Directory build does not exist"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-artifacts
          path: build/web/
