name: Build WASM Game with emsdk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List directory contents after checkout
        run: ls -R  # Verifica che p/main.py e i file locali siano presenti

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pygbag
          git clone https://github.com/emscripten-core/emsdk.git

      - name: Build WASM Game with local template
        run: |
          set -e  # Interrompe se c'è un errore
          set -x  # Abilita logging dettagliato
          echo "Starting the game build with local template..."
          pygbag p/main.py --template p/assets/games/default.tmpl  # Usa il template locale

      - name: List directory contents after build
        run: ls -R build || echo "Directory build does not exist"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-artifacts
          path: build/web/
